server:
  port: 8222

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/utenti/**
        - id: prodotti-service
          uri: http://localhost:8071
          predicates:
            - Path=/api/v1/prodotti

eureka:
  client:
    enabled: true

management:
  tracing:
    sampling:
      probability: 1.0