server:
  port: 8222

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: http://localhost:8070
          predicates:
            - Path=/utenti/**

        - id: user-service
          uri: http://localhost:8070
          predicates:
            - Path=/posizionelavorativa/**

        - id: user-service
          uri: http://localhost:8070
          predicates:
            - Path=/dipartimenti/**

        - id: user-service
          uri: http://localhost:8070
          predicates:
            - Path=/comuni/**

        - id: gestione-comunity
          uri: http://localhost:8002
          predicates:
            - Path=/news/**

        - id: gestione-comunity
          uri: http://localhost:8002
          predicates:
            - Path=/likes/**

        - id: gestione-comunity
          uri: http://localhost:8002
          predicates:
            - Path=/commenti/**

        - id: gestionecurriculum
          uri: http://localhost:8060
          predicates:
            - Path=/curriculum/**

        - id: gestione_personale
          uri: http://localhost:8052
          predicates:
            - Path=/comunicazioniAziendali/**

        - id: gestione_personale
          uri: http://localhost:8052
          predicates:
            - Path=/timbrature/**

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true


management:
  tracing:
    sampling:
      probability: 1.0