spring:
  application:
    name: user-service
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/user_service
    username: tiger
    password: mypassword
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

server:
  port: 8070

jwt:
  secret: "2A7D9F8B1C3E4F6A5B7D8C9E0F1A2B3C4D5E6F7A8B9C0D1E2F3A4B5C6D7E8F9"
  expiration: 3600000  # 1 ora


# Configurazioni per il server email
mail:
  username: "adriani.marco.93@gmail.com"
  password: "woaekwnrikjcyyjs"
  host: smtp.gmail.com
  port: 25
