services:
  postgresql:
    container_name: postgres_tiger_refactor
    image: postgres
    environment:
      POSTGRES_USER: tiger
      POSTGRES_PASSWORD: mypassword
      PGDATA: /data/postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - tiger_network

  mongodb:
    container_name: mongo_tiger
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: tiger
      MONGO_INITDB_ROOT_PASSWORD: mypassword
    volumes:
      - mongo:/data/db
      - mongo_config:/data/configdb
    ports:
      - "27017:27017"
    networks:
      - tiger_network

  mongo-express:
    container_name: tiger_mongo_express
    image: mongo-express:latest
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: tiger
      ME_CONFIG_MONGODB_ADMINPASSWORD: mypassword
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: tiger
      ME_CONFIG_BASICAUTH_PASSWORD: mypassword
    ports:
      - "8081:8081"
    networks:
      - tiger_network

  zookeeper: #server virtuale sul quale runna kafka
    image: confluentinc/cp-zookeeper:latest
    container_name: tiger_zookeeper
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    networks:
      - tiger_network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: tiger_kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT, PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    networks:
      - tiger_network


networks:
  tiger_network:
    driver: bridge

volumes:
  postgres:
  mongo:
  mongo_config: