server:
  port: 8222

spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: http://localhost:8070
          predicates:
            - Path=/utenti/**
            - Path=/posizionelavorativa/**
            - Path=/dipartimenti/**
            - Path=/comuni/**
        - id: gestione-comunity
          uri: http://localhost:8002
          predicates:
            - Path=/news/**
            - Path=/likes/**
            - Path=/commenti/**
        - id: gestionecurriculum
          uri: http://localhost:8060
          predicates:
            - Path=/curriculum/**
        - id: gestione_personale
          uri: http://localhost:8052
          predicates:
            - Path=/timbrature/**
            - Path=/comunicazioniAziendali/**

eureka:
  client:
    enabled: true

management:
  tracing:
    sampling:
      probability: 1.0