server:
  port: 8222

spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: http://localhost:8070
          predicates:
            - Path=/utenti/**

        - id: user-service
          uri: http://localhost:8070
          predicates:
            - Path=/posizionelavorativa/**

        - id: user-service
          uri: http://localhost:8070
          predicates:
            - Path=/dipartimenti/**

        - id: user-service
          uri: http://localhost:8070
          predicates:
            - Path=/comuni/**

        - id: gestione-comunity
          uri: http://localhost:8002
          predicates:
            - Path=/news/**

        - id: gestione-comunity
          uri: http://localhost:8002
          predicates:
            - Path=/likes/**

        - id: gestione-comunity
          uri: http://localhost:8002
          predicates:
            - Path=/commenti/**

        - id: gestionecurriculum
          uri: http://localhost:8060
          predicates:
            - Path=/curriculum/**

        - id: gestione_personale
          uri: http://localhost:8052
          predicates:
            - Path=/comunicazioniAziendali/**

        - id: gestione_personale
          uri: http://localhost:8052
          predicates:
            - Path=/timbrature/**

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true


management:
  tracing:
    sampling:
      probability: 1.0

jwt:
  secret: "2A7D9F8B1C3E4F6A5B7D8C9E0F1A2B3C4D5E6F7A8B9C0D1E2F3A4B5C6D7E8F9"
  expiration: 3600000  # 1 ora
