spring:
  application:
    name: gestione-personale
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/gestione_personale
    username: tiger
    password: mypassword
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  kafka:
    producer:
      bootstrap-server: localhost:9092
      group-id: notification-group
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: gestionePersonale:com.gruppo3.gestionePersonale.kafka.ComunicazioneConfirmation
    
server:
  port: 8052

application:
    config:
      user-url: http://localhost:5433/user_service
